# EJERCICIO 4

El conjunto de datos “Iris” ha sido usado como caso de prueba para una gran cantidad de clasificadores y es, quizás, el conjunto de datos más conocido de la literatura específica. Iris es una variedad de planta que se la desea clasificar de acuerdo a su tipo. Se reconocen tres tipos distintos: 'Iris setosa', 'Iris versicolor' e 'Iris virgínica'. El objetivo es lograr clasificar una planta de la variedad Iris a partir del largo y del ancho del pétalo y del largo y del ancho del sépalo.
El conjunto de datos Iris está formado en total por 150 muestras,
siendo 50 de cada uno de los tres tipos de plantas. Cada muestra
está compuesta por el tipo de planta, la longitud y ancho del
pétalo y la longitud y ancho del sépalo. Todos son atributos numéricos continuos.


$$
\begin{array}{|c|c|c|c|c|}
\hline X & Setosa & Versicolor & Virgínica & Inválidas \\
\hline Setosa & 50 & 0 & 0 & 0 \\
\hline Versicolor & 0 & 50 & 0 & 0 \\
\hline Virgínica & 0 & 0 & 50 & 0 \\
\hline 
\end{array}
$$


In [1]:
import pyximport; pyximport.install()
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import mpld3
%matplotlib inline
mpld3.enable_notebook()
from utils.cperceptron import Perceptron
from utils.cbackpropagation import ANN #, Identidad, Sigmoide
import utils.patrones as magia

def progreso(ann, X, T, y=None, n=-1, E=None):
    if n % 20 == 0:
        print("Pasos: {0} - Error: {1:.32f}".format(n, E)) 
def progresoPerceptron(perceptron, X, T, n):
    y = perceptron.evaluar(X)
    incorrectas = (T != y).sum()
    print("Pasos: {0}\tIncorrectas: {1}\n".format(n, incorrectas))

In [2]:
iris = np.load('resources/iris.npy')

In [3]:
#Armo Patrones
clases, patronesEnt, patronesTest = magia.generar_patrones(
    magia.escalar(iris[:,1:]).round(4),iris[:,:1],80)
X, T = magia.armar_patrones_y_salida_esperada(clases,patronesEnt)
clases, patronesEnt, noImporta = magia.generar_patrones(
    magia.escalar(iris[:,1:]),iris[:,:1],100)
Xtest, Ttest = magia.armar_patrones_y_salida_esperada(clases,patronesEnt)

utils/patrones.py:84: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  X = np.vstack(patrones[c] for c in clases)


a) Entrene perceptrones para que cada uno aprenda a reconocer uno de los distintos tipos de plantas Iris. Informe los parámetros usados para el entrenamiento y el desempeño obtenido. Emplee todos los patrones para el entrenamiento. Muestre la matriz de confusión para la mejor clasificación obtenida luego del entrenamiento, informando los patrones clasificados correcta e incorrectamente.

In [4]:
print("Entrenando P1:")
p1 = Perceptron(X.shape[1])
I1 = p1.entrenar_numpy(X, T[:,0], max_pasos=5000, callback=progresoPerceptron, frecuencia_callback=2500)
print("Pasos:{0}".format(I1))
print("\nEntrenando P2:")
p2 = Perceptron(X.shape[1])
I2 = p2.entrenar_numpy(X, T[:,1], max_pasos=5000, callback=progresoPerceptron, frecuencia_callback=2500)
print("Pasos:{0}".format(I2))
print("\nEntrenando P3:")
p3 = Perceptron(X.shape[1])
I3 = p3.entrenar_numpy(X, T[:,2], max_pasos=5000, callback=progresoPerceptron, frecuencia_callback=2500)
print("Pasos:{0}".format(I3))

Entrenando P1:
Pasos:5

Entrenando P2:
Pasos: 2500	Incorrectas: 66

Pasos: 5000	Incorrectas: 57

Pasos:5000

Entrenando P3:
Pasos: 2500	Incorrectas: 1

Pasos: 5000	Incorrectas: 3

Pasos:5000


In [5]:
Y = np.vstack((p1.evaluar(Xtest),p2.evaluar(Xtest),p3.evaluar(Xtest))).T
magia.matriz_de_confusion(Ttest,Y)

(array([[26.,  0.,  0., 24.],
        [ 0.,  3.,  4., 43.],
        [ 0.,  0., 50.,  0.]]),
 [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])])

b) Entrene una red neuronal artificial usando backpropagation como algoritmo de aprendizaje con el fin de lograr la clasificación pedida. Emplee todos los patrones para el entrenamiento. Detalle los parámetros usados para el entrenamiento así como la arquitectura de la red neuronal. Repita más de una vez el procedimiento para confirmar los resultados obtenidos e informe la matriz de confusión para la mejor clasificación obtenida.

In [6]:
# Crea la red neuronal
ocultas = 10
entradas = X.shape[1]
salidas = T.shape[1]
ann = ANN(entradas, ocultas, salidas)
ann.reiniciar()

In [7]:
#Entreno
E, n = ann.entrenar_rprop(X, T, min_error=0, max_pasos=100000, callback=progreso, frecuencia_callback=10000)
print("\nRed entrenada en {0} pasos con un error de {1:.32f}".format(n, E))

Pasos: 10000 - Error: 0.01105245350586019428829054334074
Pasos: 20000 - Error: 0.00832837378286719644260305273065
Pasos: 30000 - Error: 0.00714796471425109894437532886968
Pasos: 40000 - Error: 0.00677008527980307080879063263978
Pasos: 50000 - Error: 0.00622714990747834807455207695170
Pasos: 60000 - Error: 0.00509038378233723706745017523190
Pasos: 70000 - Error: 0.00339872099104934809535305539896
Pasos: 80000 - Error: 0.00211107496510057465397003362284
Pasos: 90000 - Error: 0.00120883407300922149189836840577
Pasos: 100000 - Error: 0.00076479713683649461208879927199

Red entrenada en 100000 pasos con un error de 0.00076479713683649461208879927199


In [8]:
#Evaluo
Y = (ann.evaluar(Xtest) >= 0.97)
magia.matriz_de_confusion(Ttest,Y)

(array([[50.,  0.,  0.,  0.],
        [ 0., 45.,  0.,  5.],
        [ 0.,  2., 44.,  4.]]),
 [array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1])])

In [9]:
(ann.evaluar(Xtest)[90])

array([-0.00117736,  0.99995774,  0.00176515])